version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/jsoup

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test

  deploy-artifacts:
      docker:
        - image: circleci/openjdk:8-jdk

      working_directory: ~/jsoup

      steps:
        - checkout

        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "pom.xml" }}

        - run: mvn dependency:go-offline

        - run: mvn clean

        - run: mvn versions:set -DnewVersion=$CIRCLE_TAG

        - run: mvn install

        - run:
              name: Install jFrog CLI
              command: curl -fL https://getcli.jfrog.io | sh

        - run:
            name: Push to Artifactory
            command: |
              set -x
              ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --password $ARTIFACTORY_PASSWORD --interactive=false
              ./jfrog rt u "target/jsoup-*" libs-release-local/org/jsoup/jsoup-cogniteev/$CIRCLE_TAG/ --build-name=org.jsoup:jsoup-cogniteev --build-number=$CIRCLE_TAG
              ./jfrog rt bce org.jsoup:jsoup-cogniteev $CIRCLE_TAG
              ./jfrog rt bp org.jsoup:jsoup-cogniteev $CIRCLE_TAG

workflows:
  version: 2

  run-tests:
    jobs:
      - build:
          filters:
            branches:
              ignore: master

  publish-release:
    jobs:
      - deploy-artifacts:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
